"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

type CompareForm = {
  age: string;
  income: string;
  savings: string;
  property: string;
};

type ReportResult = {
  rankPercent: number;
  lifeScore: number;
};

const initialForm: CompareForm = {
  age: "",
  income: "",
  savings: "",
  property: "no"
};

export default function ComparePage() {
  const router = useRouter();
  const [form, setForm] = useState<CompareForm>(initialForm);
  const [showReport, setShowReport] = useState(false);
  const [report, setReport] = useState<ReportResult | null>(null);
  const [shareStatus, setShareStatus] = useState("");

  const onSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const age = Number(form.age);
    const income = Number(form.income);
    const savings = Number(form.savings);
    const hasProperty = form.property === "yes";

    const incomeScore = Math.min((income / 200000) * 40, 40);
    const savingsScore = Math.min((savings / 500000) * 40, 40);
    const propertyScore = hasProperty ? 15 : 0;
    const ageScore = age >= 30 && age <= 55 ? 5 : 0;

    const lifeScore = Math.max(
      1,
      Math.min(100, Math.round(incomeScore + savingsScore + propertyScore + ageScore))
    );
    const rankPercent = Math.max(1, Math.min(95, 100 - Math.round(lifeScore * 0.8)));

    setReport({ rankPercent, lifeScore });
    setShareStatus("");
    setShowReport(true);
  };

  const handleShareRank = async () => {
    if (!report) return;

    const rank = report.rankPercent;
    const shareText = `I'm Top ${rank}%\nBut not in the Top 10% yet\nCan you beat me?`;
    const canvas = document.createElement("canvas");
    canvas.width = 1080;
    canvas.height = 1080;
    const context = canvas.getContext("2d");

    if (!context) return;

    const gradient = context.createLinearGradient(0, 0, canvas.width, canvas.height);
    gradient.addColorStop(0, "#2563eb");
    gradient.addColorStop(1, "#1e3a8a");
    context.fillStyle = gradient;
    context.fillRect(0, 0, canvas.width, canvas.height);

    context.fillStyle = "rgba(255,255,255,0.2)";
    context.fillRect(70, 70, canvas.width - 140, canvas.height - 140);

    context.fillStyle = "#ffffff";
    context.textAlign = "center";
    context.font = "700 96px Inter, Arial, sans-serif";
    context.fillText(`I'm Top ${rank}%`, canvas.width / 2, 410);
    context.font = "600 54px Inter, Arial, sans-serif";
    context.fillText("But not in the Top 10% yet", canvas.width / 2, 530);
    context.fillText("Can you beat me?", canvas.width / 2, 620);
    context.font = "500 32px Inter, Arial, sans-serif";
    context.fillText("Generated by CompareMe AI", canvas.width / 2, 780);

    const downloadLink = document.createElement("a");
    downloadLink.href = canvas.toDataURL("image/png");
    downloadLink.download = `compareme-top-${rank}.png`;
    downloadLink.click();

    try {
      await navigator.clipboard.writeText(shareText);
      setShareStatus("Image downloaded. Share text copied to clipboard.");
    } catch {
      setShareStatus("Image downloaded. Copy text manually from the card.");
    }
  };

  return (
    <main className="mx-auto flex max-w-4xl flex-col items-center px-4 py-16 text-center sm:py-24">
      <section className="w-full rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">
        <h1 className="text-3xl font-bold text-slate-900 sm:text-4xl">
          CompareMe AI
        </h1>
        <p className="mt-3 text-slate-600">
          Enter your details to generate a quick comparison report.
        </p>

        <form className="mx-auto mt-8 grid max-w-xl gap-4 text-left" onSubmit={onSubmit}>
          <label className="text-sm font-medium text-slate-700">
            Age
            <input
              required
              type="number"
              min="0"
              value={form.age}
              onChange={(e) => setForm({ ...form, age: e.target.value })}
              className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-200"
            />
          </label>

          <label className="text-sm font-medium text-slate-700">
            Income
            <input
              required
              type="number"
              min="0"
              value={form.income}
              onChange={(e) => setForm({ ...form, income: e.target.value })}
              className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-200"
            />
          </label>

          <label className="text-sm font-medium text-slate-700">
            Savings
            <input
              required
              type="number"
              min="0"
              value={form.savings}
              onChange={(e) => setForm({ ...form, savings: e.target.value })}
              className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-200"
            />
          </label>

          <label className="text-sm font-medium text-slate-700">
            Property (yes/no)
            <select
              value={form.property}
              onChange={(e) => setForm({ ...form, property: e.target.value })}
              className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 outline-none transition focus:border-brand-500 focus:ring-2 focus:ring-brand-200"
            >
              <option value="yes">Yes</option>
              <option value="no">No</option>
            </select>
          </label>

          <button
            type="submit"
            className="mt-2 rounded-lg bg-brand-600 px-5 py-3 text-sm font-semibold text-white transition hover:bg-brand-700"
          >
            Generate Report
          </button>
        </form>

        {showReport && (
          <div className="mx-auto mt-8 max-w-xl space-y-5">
            <div className="rounded-xl bg-brand-50 p-6 text-center">
              <h2 className="text-lg font-semibold text-brand-700">Your Report</h2>
              <p className="mt-3 whitespace-pre-line text-slate-700">
                {`You are ahead of most people.\n\nYou are currently in the top ${report?.rankPercent ?? 35}%.\n\nWithout a clear strategy,\nyou are likely to stay in this position for years.`}
              </p>
              <p className="mt-4 text-sm font-medium text-brand-700">
                Estimated Life Score: {report?.lifeScore ?? 74}/100
              </p>
            </div>

            <div className="rounded-2xl bg-gradient-to-br from-brand-600 to-blue-900 p-6 text-center text-white shadow-md">
              <p className="text-4xl font-bold">
                I&apos;m Top {report?.rankPercent ?? 35}%
              </p>
              <p className="mt-3 text-xl font-semibold">But not in the Top 10% yet</p>
              <p className="mt-2 text-xl font-semibold">Can you beat me?</p>
              <button
                type="button"
                onClick={() => void handleShareRank()}
                className="mt-6 rounded-xl bg-white px-6 py-3 text-sm font-bold text-brand-700 transition hover:bg-brand-50"
              >
                Share My Rank
              </button>
              {shareStatus && <p className="mt-3 text-xs text-blue-100">{shareStatus}</p>}
            </div>

            <div className="rounded-2xl border border-brand-200 bg-gradient-to-b from-white to-brand-50 p-6 text-center shadow-md">
              <p className="inline-flex rounded-full bg-brand-100 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-brand-700">
                Premium Upgrade
              </p>
              <h3 className="mt-4 text-2xl font-bold text-slate-900">
                Unlock Your Path to the Top 10%
              </h3>
              <p className="mt-3 text-sm leading-6 text-slate-600">
                See exactly what steps you need to take to move into the top 10%.
              </p>
              <div className="mx-auto mt-5 max-w-md rounded-xl border border-brand-100 bg-white/90 p-4 text-left">
                <p className="text-sm font-semibold text-slate-900">What you will get</p>
                <ul className="mt-3 space-y-2 text-sm text-slate-700">
                  <li>• A personalized financial roadmap</li>
                  <li>• Exact steps to reach top 10%</li>
                  <li>• Income growth strategy</li>
                  <li>• Investment &amp; savings plan</li>
                </ul>
              </div>
              <button
                type="button"
                className="mt-6 rounded-xl bg-brand-600 px-7 py-3 text-sm font-semibold text-white shadow-lg shadow-brand-200 transition hover:bg-brand-700"
                onClick={() => router.push("/contact?plan=full-report")}
              >
                Unlock My Plan to Reach Top 10% – $9.99/month
              </button>
              <p className="mt-3 text-xs leading-5 text-slate-600">
                Most people stay stuck in the same bracket for 10+ years. Don&apos;t be one
                of them.
              </p>
            </div>
          </div>
        )}
      </section>
    </main>
  );
}
